### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by YinengXiong** [mrsempress/OBMO_GUPNet#1]
When will the code of training version of OBMO release?

**Comment by afoxxvi** [comment]
Same question

**Comment by mrsempress** [comment]
Thanks for your interest in our work. However, this code will not be organized for now due to other important work recently (struggling to graduate). The corresponding checkpoint, offline OBMO usage method, and [PatchNet-based codes](https://github.com/mrsempress/OBMO) have been released. You can also implement it yourself according to the instructions in the paper. Follow-up work will be sorted out after completion according to priority. If you have any questions about the understanding of the paper, you can leave a message. We will reply at our leisure.

**Comment by afoxxvi** [comment]
Thanks for your reply, I am new in this field and now trying to implement OBMO module in MonoFlex, but its data loader class is quite different from PatchNet but similar to GUPNet, so I wonder if I should change the location gt label in \_\_getitem__ method of kitti.py(), or create pseudo labels and store them to new files as a single task before training?
