### ISSUE TITLE
Don't understand the code

### ISSUE THREAD

**Issue by JCZ404** [mrsempress/OBMO_GUPNet#2]
Hi, thanks for your great work. When I read the code, I felt little bit confused. In the provided `offline_OBMO.py`, you calculate the epsilons and _epsilons. The former one is the depth shift relative ratios, i.g (4%, 2%, 1%, -1%, -2%, -4%), when calculate the _epsilons, you multiply these ratios with the depth of current 3D object, which result in the shift distance along the depth dimension, i.g(0.93 meters). But in the following loop, you update the shifted depth value with ` new_p[12] = p[13].astype(np.float32) * (1 + e)`, where `e` is the shift distance. This is weird, since if we update the depth value like this, the depth value of new_p will be greatly away from the original depth value, is this correct? or the `e` in the loop is actually the shift ratio, i.e 4%? Another question is the update rule of the `max_iou`. In your code, when `iou > max_iou` you update the iou with max_iou, rather than update max_iou with iou, this makes me confused. Besides, I also don't understand why we need set this condition of iou to decide whether we need to get a shifted 3D bounding box. Since the object far from camera will always result in large iou, that means if we set such iou condition, we shift the 3D bounding boxes near the camera more frequently and seldom shift the 3D bounding boxes far from the camera. Hope to get your reply. Thanks!
![image](https://user-images.githubusercontent.com/51013927/231037383-856c3a07-be34-4665-b849-1d2f9a95c95f.png)

**Comment by mrsempress** [comment]
Thank you for your attention to our work. The replies to your confusion are as follows.
1. That's right. As we said in the article "One bounding box, multiple objects," even if the distance between two objects is large, they may still have similar semantic information.
2. This errata should be corrected to `max_iou=iou.`
3. Because we want to keep the bounding box while moving the object, we control it through IoU. It is reasonable that remote objects should be rarely shifted. Compared to nearby objects, remote objects moving at the same depth delta will change the object shape more excellently, which significantly impacts the bounding box. However, the size of each category of objects has a priori value, so the moving range of remote objects is relatively small.

**Comment by JCZ404** [comment]
Thanks for your kind reply. For (1), you mean the loop is conduct on the `_epsilons` is right? It seems doesn't make sense if following such update rule. For example, `epsilons` contains `[4%, 2%, 1%, -1%, -2%, -4%]`, let's set the original GT depth value is 50 meters, after multiplying the depth value, we get the `_epsilons` which contains `[2, 1, 0.5, -0.5, -1, -2]`. So when do the for loop, we will update the depth of `new_p` with `50 x (1+2)`, which I don't understand the meaning of this calculation. Is this right? Correct me if I'm wrong.

**Comment by mrsempress** [comment]
It should be `50 + 2`. We correct it Now. Sorry for the confusion caused by our carelessness.
